version: '3'

services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=trust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5442:5432"
    container_name: database